// PURPOSE: Module declarations and re-exports for output-report (orchestrators, formatters, VOs, constants)
pub mod agent_output_orchestrator;
pub use agent_output_orchestrator::OutputClientOrchestrator;
pub mod agent_commands_orchestrator;
pub use agent_commands_orchestrator::ReportCommandsOrchestrator;
pub mod capabilities_reporting_formatter;
pub use capabilities_reporting_formatter::ReportFormatterProcessor;
pub mod contract_client_aggregate;
pub use contract_client_aggregate::OutputClientAggregate;
pub mod contract_output_aggregate;
pub mod taxonomy_position_vo;
pub use taxonomy_position_vo::Position;
pub mod taxonomy_result_vo;
pub use taxonomy_result_vo::{LintResult, LintResultList};
pub mod taxonomy_score_constant;
pub use taxonomy_score_constant::{FORMAT_JSON, FORMAT_JUNIT, FORMAT_SARIF, FORMAT_TEXT};
pub mod taxonomy_score_vo;
pub use taxonomy_score_vo::{compute_score, FileFormat};
pub mod taxonomy_severity_vo;
pub use taxonomy_severity_vo::Severity;
