use std::sync::Arc;
/// Plugin and adapter-related CLI commands for auto-linter.
use crate::taxonomy::{AccessDeniedError,
ActionArgs,
ActionName,
ActualValue,
AdapterClassMap,
AdapterEntry,
AdapterError,
AdapterMetadata,
AdapterMetadataList,
AdapterName,
AdapterNameList,
AdapterRegistered,
AdapterStatus,
AgentStatus,
AgentStatusVO};
use crate::taxonomy::{AggregatedResults,
AppConfig,
ArchitectureConfig,
ArchitectureRule,
BooleanVO,
CallChainError,
CallChainList,
CapabilityReference,
CapabilityReferenceList,
CapabilityRoutingContext,
Cause,
ClassDefinitionMap,
ClassFileMap,
ClassMethodsVO,
ClassNameVO};
use crate::taxonomy::{ClassPath,
ClassUsageItem,
ClassUsageItemList,
ClassUsageMap,
ColumnNumber,
CommandArgs,
CommandMetadataVO,
ComplianceStatus,
ConfigError,
ConfigKey,
Constraint,
ContentString,
Count,
CustomMessageVO,
DataFlowList};
use crate::taxonomy::{DescriptionVO,
DirectoryPath,
DiscoveryError,
DoctorResultVO,
Duration,
EnvContentVO,
ErrorCode,
ErrorMessage,
ExitCode,
ExpectedValue,
FieldName,
FileContentVO,
FileDefinitionMap,
FileFormat,
FilePath};
use crate::taxonomy::{FilePathList,
FileSystemError,
FixApplied,
FixResult,
GitDiffResultVO,
GitHookError,
GitRef,
GovernanceReport,
GraphAnalysisContext,
HookInstalled,
HookRemoved,
Identity,
ImportGraph,
ImportInfo,
ImportInfoList};
use crate::taxonomy::{ImportNameList,
InboundLinkMap,
InheritanceMap,
IntoPatternListValues,
JobError,
JobId,
JobIdList,
JobStatus,
LayerDefinition,
LayerMapVO,
LayerNameVO,
LegacyLayerRule,
LegacyLayerRuleList,
LineContentList,
LineContentVO};
use crate::taxonomy::{LineNumber,
LintMessage,
LintResult,
LintResultList,
LintStatusActionArgs,
LinterOperationError,
Location,
LocationList,
LogOutput,
MaintenanceStatsVO,
MandatoryImportRuleVO,
McpConfigVO,
MetadataVO,
MetricsError,
ModuleName};
use crate::taxonomy::{ModuleToFileMap,
NameVariants,
NamingConfig,
NamingError,
OrphanIndicatorResult,
PathNotFoundError,
PatternList,
PluginError,
PluginGroup,
Position,
PrimitiveTypeList,
PrimitiveTypeName,
PrimitiveViolation,
PrimitiveViolationList,
ProjectConfig};
use crate::taxonomy::{ProjectResult,
ReachabilityResult,
RegistrationError,
RenamedFile,
RenamedFileList,
ResponseData,
ResponseDataList,
ScanCompleted,
ScanError,
ScanFailed,
ScanStarted,
ScopeBounds,
ScopeRef,
ScopeResolutionError,
Score};
use crate::taxonomy::{SemanticError,
Severity,
SourceParserError,
StdError,
StdOutput,
SuccessStatus,
SuffixPolicyVO,
SuffixVO,
Suggestion,
SymbolName,
SymbolNameList,
SyntaxErrorVO,
Thresholds,
Timeout,
Timestamp};
use crate::taxonomy::{TransportEndpoint,
TransportError,
TransportProtocol,
TransportUrlVO,
ValidationError,
ViolationConstraint,
WatchEventError,
WatchResult,
WatchServiceError,
WatchSubscriptionError};
use crate::contract::{AdapterContainerAggregate,
AgentLifecycleAggregate,
AnalysisOrchestratorAggregate,
ArchCoordinatorAggregate,
CapabilityContainerAggregate,
CheckCommandsAggregate,
ContainerRegistryAggregate,
DevCommandsAggregate,
DirectoryWatchAggregate,
FixCommandsAggregate,
GitCommandsAggregate,
GitDiffResultAggregate,
HookManagementOrchestratorAggregate,
IAnalyzer,
IArchAnalyzerProtocol};
use crate::contract::{IArchCompliancePort,
IArchComplianceProtocol,
IArchImportProcessorProtocol,
IArchImportProtocol,
IArchInheritanceProtocol,
IArchLintProtocol,
IArchOrphanProtocol,
IArchRuleEngineProtocol,
IArchRuleProtocol,
IArchStructureProtocol,
ICodeQualityProtocol,
ICodeTransformationProtocol,
ICommandExecutorPort,
IConfigDiscoveryPort,
IConfigParserPort};
use crate::contract::{IConfigProviderPort,
IConfigRulesProtocol,
IConfigValidationPort,
ICycleAnalysisProtocol,
IDataFlowProtocol,
IDispatchRoutingParserProtocol,
IDispatchRoutingProtocol,
IDomainTypeProtocol,
IHookManagerPort,
IHttpProviderPort,
IInternalCheckerProtocol,
IJavascriptFlowPort,
IJavascriptScopePort,
IJobRegistryPort,
ILintReportingProtocol};
use crate::contract::{IMcpServerPort,
IMetricAnalyzerProtocol,
IMetricCheckerProtocol,
IMetricsProviderPort,
INamingCheckerProtocol,
INamingProviderPort,
INamingRuleProtocol,
INamingVariantPort,
INamingVariantProtocol,
IOrphanGraphProtocol,
IOrphanIndicatorProtocol,
IPathNormalizationPort,
IPluginManagerPort,
IRoleCheckerProtocol,
IScannerProviderPort};
use crate::contract::{IScopeBoundaryProtocol,
ISemanticTracerPort,
ISemanticTracerProtocol,
ISetupManagementProtocol,
ISourceParserPort,
IUnusedProtocol,
IWatchProviderPort,
InfrastructureContainerAggregate,
JobRegistryAggregate,
LintFixOrchestratorAggregate,
LintPipelineOrchestratorAggregate,
MaintenanceCommandsAggregate,
MultiProjectAggregate,
MultiProjectOrchestratorAggregate,
OrchestratorContainerAggregate};
use crate::contract::{OutputClientAggregate,
PipelineActionDispatcherAggregate,
PipelineExecutionOrchestratorAggregate,
PipelineExtendedOrchestratorAggregate,
PluginCommandsAggregate,
ProjectContainerAggregate,
ReportCommandsAggregate,
ServiceContainerAggregate,
SetupManagementAggregate,
ToolHandler,
WatchCommandsAggregate,
WatchExecutionOrchestratorAggregate};
pub struct PluginCommandsSurface {
    pub container: Option<Arc<dyn ServiceContainerAggregate>>,
}

impl PluginCommandsSurface {
    pub fn new() -> Self {
        Self { container: None }
    }

    pub fn register_all(&mut self, container: Arc<dyn ServiceContainerAggregate>) {
        self.container = Some(container);
    }

    pub fn adapters(&self) {
        println!("Enabled Adapters:");
        // In real impl: iterate self.container.adapters
        println!(" - ruff");
        println!(" - mypy");
        println!(" - bandit");
        println!(" - radon");
        println!(" - architecture");
    }

    pub fn plugins(&self) {
        println!("Discovered Plugins:");
        println!("No plugins or custom adapters found.");
        println!("\nTo register a plugin, add entry point in Cargo.toml:");
        println!("  [lib.adapter]");
        println!("  my_adapter = my_package::MyAdapterClass");
    }
}

pub fn register_plugin_commands(container: Arc<dyn ServiceContainerAggregate>) -> PluginCommandsSurface {
    let mut surface = PluginCommandsSurface::new();
    surface.register_all(container);
    surface
}
