use std::sync::Arc;
use std::collections::HashMap;
/// MCP Health Check Surface.
use crate::taxonomy::{AccessDeniedError,
ActionArgs,
ActionName,
ActualValue,
AdapterClassMap,
AdapterEntry,
AdapterError,
AdapterMetadata,
AdapterMetadataList,
AdapterName,
AdapterNameList,
AdapterRegistered,
AdapterStatus,
AgentStatus,
AgentStatusVO};
use crate::taxonomy::{AggregatedResults,
AppConfig,
ArchitectureConfig,
ArchitectureRule,
BooleanVO,
CallChainError,
CallChainList,
CapabilityReference,
CapabilityReferenceList,
CapabilityRoutingContext,
Cause,
ClassDefinitionMap,
ClassFileMap,
ClassMethodsVO,
ClassNameVO};
use crate::taxonomy::{ClassPath,
ClassUsageItem,
ClassUsageItemList,
ClassUsageMap,
ColumnNumber,
CommandArgs,
CommandMetadataVO,
ComplianceStatus,
ConfigError,
ConfigKey,
Constraint,
ContentString,
Count,
CustomMessageVO,
DataFlowList};
use crate::taxonomy::{DescriptionVO,
DirectoryPath,
DiscoveryError,
DoctorResultVO,
Duration,
EnvContentVO,
ErrorCode,
ErrorMessage,
ExitCode,
ExpectedValue,
FieldName,
FileContentVO,
FileDefinitionMap,
FileFormat,
FilePath};
use crate::taxonomy::{FilePathList,
FileSystemError,
FixApplied,
FixResult,
GitDiffResultVO,
GitHookError,
GitRef,
GovernanceReport,
GraphAnalysisContext,
HookInstalled,
HookRemoved,
Identity,
ImportGraph,
ImportInfo,
ImportInfoList};
use crate::taxonomy::{ImportNameList,
InboundLinkMap,
InheritanceMap,
IntoPatternListValues,
JobError,
JobId,
JobIdList,
JobStatus,
LayerDefinition,
LayerMapVO,
LayerNameVO,
LegacyLayerRule,
LegacyLayerRuleList,
LineContentList,
LineContentVO};
use crate::taxonomy::{LineNumber,
LintMessage,
LintResult,
LintResultList,
LintStatusActionArgs,
LinterOperationError,
Location,
LocationList,
LogOutput,
MaintenanceStatsVO,
MandatoryImportRuleVO,
McpConfigVO,
MetadataVO,
MetricsError,
ModuleName};
use crate::taxonomy::{ModuleToFileMap,
NameVariants,
NamingConfig,
NamingError,
OrphanIndicatorResult,
PathNotFoundError,
PatternList,
PluginError,
PluginGroup,
Position,
PrimitiveTypeList,
PrimitiveTypeName,
PrimitiveViolation,
PrimitiveViolationList,
ProjectConfig};
use crate::taxonomy::{ProjectResult,
ReachabilityResult,
RegistrationError,
RenamedFile,
RenamedFileList,
ResponseData,
ResponseDataList,
ScanCompleted,
ScanError,
ScanFailed,
ScanStarted,
ScopeBounds,
ScopeRef,
ScopeResolutionError,
Score};
use crate::taxonomy::{SemanticError,
Severity,
SourceParserError,
StdError,
StdOutput,
SuccessStatus,
SuffixPolicyVO,
SuffixVO,
Suggestion,
SymbolName,
SymbolNameList,
SyntaxErrorVO,
Thresholds,
Timeout,
Timestamp};
use crate::taxonomy::{TransportEndpoint,
TransportError,
TransportProtocol,
TransportUrlVO,
ValidationError,
ViolationConstraint,
WatchEventError,
WatchResult,
WatchServiceError,
WatchSubscriptionError};
use crate::contract::{AdapterContainerAggregate,
AgentLifecycleAggregate,
AnalysisOrchestratorAggregate,
ArchCoordinatorAggregate,
CapabilityContainerAggregate,
CheckCommandsAggregate,
ContainerRegistryAggregate,
DevCommandsAggregate,
DirectoryWatchAggregate,
FixCommandsAggregate,
GitCommandsAggregate,
GitDiffResultAggregate,
HookManagementOrchestratorAggregate,
IAnalyzer,
IArchAnalyzerProtocol};
use crate::contract::{IArchCompliancePort,
IArchComplianceProtocol,
IArchImportProcessorProtocol,
IArchImportProtocol,
IArchInheritanceProtocol,
IArchLintProtocol,
IArchOrphanProtocol,
IArchRuleEngineProtocol,
IArchRuleProtocol,
IArchStructureProtocol,
ICodeQualityProtocol,
ICodeTransformationProtocol,
ICommandExecutorPort,
IConfigDiscoveryPort,
IConfigParserPort};
use crate::contract::{IConfigProviderPort,
IConfigRulesProtocol,
IConfigValidationPort,
ICycleAnalysisProtocol,
IDataFlowProtocol,
IDispatchRoutingParserProtocol,
IDispatchRoutingProtocol,
IDomainTypeProtocol,
IHookManagerPort,
IHttpProviderPort,
IInternalCheckerProtocol,
IJavascriptFlowPort,
IJavascriptScopePort,
IJobRegistryPort,
ILintReportingProtocol};
use crate::contract::{IMcpServerPort,
IMetricAnalyzerProtocol,
IMetricCheckerProtocol,
IMetricsProviderPort,
INamingCheckerProtocol,
INamingProviderPort,
INamingRuleProtocol,
INamingVariantPort,
INamingVariantProtocol,
IOrphanGraphProtocol,
IOrphanIndicatorProtocol,
IPathNormalizationPort,
IPluginManagerPort,
IRoleCheckerProtocol,
IScannerProviderPort};
use crate::contract::{IScopeBoundaryProtocol,
ISemanticTracerPort,
ISemanticTracerProtocol,
ISetupManagementProtocol,
ISourceParserPort,
IUnusedProtocol,
IWatchProviderPort,
InfrastructureContainerAggregate,
JobRegistryAggregate,
LintFixOrchestratorAggregate,
LintPipelineOrchestratorAggregate,
MaintenanceCommandsAggregate,
MultiProjectAggregate,
MultiProjectOrchestratorAggregate,
OrchestratorContainerAggregate};
use crate::contract::{OutputClientAggregate,
PipelineActionDispatcherAggregate,
PipelineExecutionOrchestratorAggregate,
PipelineExtendedOrchestratorAggregate,
PluginCommandsAggregate,
ProjectContainerAggregate,
ReportCommandsAggregate,
ServiceContainerAggregate,
SetupManagementAggregate,
ToolHandler,
WatchCommandsAggregate,
WatchExecutionOrchestratorAggregate};
pub struct McpHealthCheckSurface {
    pub container: Option<Arc<dyn ServiceContainerAggregate>>,
}

impl McpHealthCheckSurface {
    pub fn new(container: Option<Arc<dyn ServiceContainerAggregate>>) -> Self {
        Self { container }
    }

    pub async fn execute_check(&self) -> HashMap<String, serde_json::Value> {
        let mut result = HashMap::new();
        result.insert("success".to_string(), serde_json::Value::Bool(true));
        result.insert("data".to_string(), serde_json::json!({
            "lifecycle": {"status": "healthy", "uptime_seconds": 0},
            "system": {"os": "linux", "python": "3.12"},
            "components": {"ruff": "OK", "mypy": "OK", "jobs": {"running": 0, "total": 0}}
        }));
        result
    }

    pub async fn format_health_report(&self) -> String {
        let result = self.execute_check().await;
        if !result.get("success").and_then(|v| v.as_bool()).unwrap_or(false) {
            return format!("SYSTEM CRITICAL: {:?}", result.get("error"));
        }

        let report = vec![
            "=== AUTO-LINTER SYSTEM HEALTH ===".to_string(),
            "Status  : HEALTHY".to_string(),
            "Uptime  : 0s".to_string(),
            "Platform: linux (Python 3.12)".to_string(),
            "--- Components ---".to_string(),
            "Ruff      : OK".to_string(),
            "Mypy      : OK".to_string(),
            "Jobs      : 0/0 jobs active".to_string(),
        ];
        report.join("\n")
    }
}

pub fn register_health_commands(container: Arc<dyn ServiceContainerAggregate>) -> McpHealthCheckSurface {
    McpHealthCheckSurface::new(Some(container))
}
