pub mod cli_analysis_command;
pub mod cli_check_command;
pub mod cli_core_command;
pub mod cli_dev_command;
pub mod cli_fix_command;
pub mod cli_main_handler;
pub mod cli_maintenance_command;
pub mod cli_output_controller;
pub mod cli_setup_command;
pub mod cli_setup_controller;
pub mod cli_watch_command;
pub mod core_git_command;
pub mod core_multi_command;
pub mod core_plugin_command;
pub mod core_report_command;
pub mod mcp_client_handler;
pub mod mcp_command_handler;
pub mod mcp_execute_command;
pub mod mcp_health_handler;
pub mod mcp_job_handler;
pub mod mcp_server_handler;
pub mod mcp_tools_command;
pub mod mcp_tools_handler;
pub mod syspath_bootstrap_handler;

pub use cli_analysis_command::{AnalysisCommandsSurface, register_analysis_commands};
pub use cli_check_command::{CheckCommandsSurface, register_check_commands};
pub use cli_core_command::{Cli, Commands, ConfigCommands, CoreCommandsSurface, SetupCommands, get_cli, get_surface};
pub use cli_dev_command::{DevCommandsSurface, register_dev_commands};
pub use cli_fix_command::{FixCommandsSurface, register_fix_commands};
pub use cli_main_handler::{MainHandlerSurface, run_cli_entry};
pub use cli_maintenance_command::{MaintenanceCommandsSurface, register_maintenance_commands};
pub use cli_output_controller::{OutputControllerSurface, get_output_dir, set_container, tee_stdout, write_output};
pub use cli_setup_command::{SetupCommandsSurface, get_setup, register_setup_commands};
pub use cli_setup_controller::{SetupManagementSurface, generate_env, generate_mcp_config, mcp_config_claude, mcp_config_hermes, mcp_config_vscode, register_setup_management};
pub use cli_watch_command::{WatchCommandsSurface, WatchdogBridge, register_watch_command};
pub use core_git_command::{GitCommandsSurface, register_git_commands};
pub use core_multi_command::{MultiCommandsSurface, register_multi_commands};
pub use core_plugin_command::{PluginCommandsSurface, register_plugin_commands};
pub use core_report_command::{ReportCommandsSurface, register_report_commands};
pub use mcp_client_handler::{McpDesktopClientSurface, register_desktop_client};
pub use mcp_command_handler::{CommandEntry, McpCommandCatalogSurface, list_commands_func, register_catalog_commands, register_list_commands, register_read_skill_context};
pub use mcp_execute_command::{_running_jobs, register_execute_commands};
pub use mcp_health_handler::{McpHealthCheckSurface, register_health_commands};
pub use mcp_job_handler::{McpJobCommandsSurface};
pub use mcp_server_handler::{McpServerHandlerSurface};
pub use mcp_tools_command::{commands_schema_tool, health_check_tool, list_commands_tool, read_skill_context_tool};
pub use mcp_tools_handler::{register_tools};
pub use syspath_bootstrap_handler::{SyspathBootstrapHandler};
