// PURPOSE: Module declarations for git-hooks (orchestrators, adapters, container)
pub use shared::git_hooks::contract_commands_aggregate::GitCommandsAggregate;
pub use shared::git_hooks::contract_manager_port::IHookManagerPort;
pub use shared::git_hooks::contract_orchestrator_aggregate::HookManagementOrchestratorAggregate;
pub use shared::git_hooks::taxonomy_diff_result_vo::GitDiffResultVO;
pub use shared::git_hooks::taxonomy_hook_error::GitHookError;
pub use shared::git_hooks::taxonomy_installed_event::HookInstalled;
pub use shared::git_hooks::taxonomy_ref_vo::GitRef;
pub use shared::git_hooks::taxonomy_removed_event::HookRemoved;
pub mod agent_commands_orchestrator;
pub use agent_commands_orchestrator::GitCommandsOrchestrator;
pub mod agent_management_orchestrator;
pub use agent_management_orchestrator::HookManagementOrchestrator;
pub mod agent_dev_orchestrator;
pub use agent_dev_orchestrator::DevCommandsOrchestrator;
pub mod infrastructure_diff_scanner;
pub use infrastructure_diff_scanner::{DiffResult, GitDiffScanner};
pub mod infrastructure_hook_adapter;
pub use infrastructure_hook_adapter::GitHookAdapter;
pub mod root_git_hooks_container;
