[package]
name = "cli-commands"
version = "3.6.1"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shared = { workspace = true }
dispatcher = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
ctrlc = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
tempfile = "3"

[[bench]]
name = "bench_cli_commands"
path = "benches/bench_cli_commands.rs"
harness = false
