[package]
name = "external-lint-lint-arwaky"
version = "3.6.0"
edition = "2024"
description = "External linter adapters (clippy, ruff, eslint, etc.)."
license = "MIT"
repository = "https://github.com/rakaarwaky/lint-arwaky"

[dependencies]
shared = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
filesystem = { workspace = true }
config-system = { workspace = true }
criterion = { version = "0.8.2", features = ["html_reports"] }

[lints]
workspace = true

[[bench]]
name = "bench_external_lint"
path = "benches/bench_external_lint.rs"
harness = false
