// PURPOSE: SetupProcessor — processes project setup steps (env, gitignore, config, hooks)
//
// Implements ISetupManagementProtocol — the capabilities layer for project initialization.
// Handles:
//   - Environment file generation (.env with PHANTOM_ROOT for JS tools)
//   - MCP configuration generation in 3 formats (Claude, Hermes, VS Code)
//   - Binary discovery for lint-arwaky-mcp (current exe dir, CARGO_HOME, PATH)
//   - Language detection (rust crates/, python pyproject.toml, js package.json)
//   - Config file template loading from embedded YAML files
//   - XDG config directory creation

use shared::common::taxonomy_job_vo::{EnvContentVO, McpConfigVO, SuccessStatus};
use shared::common::taxonomy_suggestion_vo::DescriptionVO;
use shared::filesystem::contract_filesystem_aggregate::IFilesystemAggregate;
use shared::project_setup::ISetupManagementProtocol;
use shared::project_setup::taxonomy_setup_contract_vo::{
    CreateConfigDirResult, McpBinaryNameVO, ProjectLanguageVO, ProjectLanguagesVO, SetupError,
    WriteConfigResult,
};

use std::collections::HashMap;
use std::sync::Arc;

// ─── Block 1: Struct Definition ───────────────────────────

/// Business logic for generating setup and configuration artifacts.
pub struct SetupManagementProcessor {
    installer: Arc<dyn shared::project_setup::ISetupInstallerProtocol>,
    filesystem: Arc<dyn IFilesystemAggregate>,
}

// ─── Block 2: Protocol Trait Implementation ───────────────

impl ISetupManagementProtocol for SetupManagementProcessor {
    /// Generate .env content for the lint-arwaky environment.
    fn generate_env(&self, home: &shared::common::taxonomy_path_vo::DirectoryPath) -> EnvContentVO {
        let _ = self
            .filesystem
            .create_dir_all(std::path::Path::new(&home.value));
        let lines = [
            "# Lint Arwaky Environment Configuration".to_string(),
            "# Generated by: lint-arwaky init".to_string(),
            "".to_string(),
            "# Phantom root (for JS/TS linters):".to_string(),
            format!("PHANTOM_ROOT={}/", home.value),
        ];
        EnvContentVO::new(lines.join("\n") + "\n")
    }

    /// Generate the base mcp.json entry for lint-arwaky.
    fn generate_mcp_config(&self) -> McpConfigVO {
        let mut config = HashMap::new();
        let server_entry = serde_json::json!({
            "command": "lint-arwaky",
            "args": [],
            "alwaysAllow": ["lint", "execute_command", "health_check", "list_commands", "read_skill_context"]
        });
        config.insert("lint-arwaky".to_string(), server_entry);
        McpConfigVO::new(config)
    }

    /// Generate Claude Desktop MCP config format.
    fn mcp_config_claude(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert("mcpServers".to_string(), serde_json::json!(base.value()));
        McpConfigVO::new(config)
    }

    /// Generate Hermes/Antigravity MCP config format.
    fn mcp_config_hermes(&self) -> McpConfigVO {
        self.generate_mcp_config()
    }

    /// Generate VS Code MCP config format.
    fn mcp_config_vscode(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert(
            "mcp".to_string(),
            serde_json::json!({"servers": base.value()}),
        );
        McpConfigVO::new(config)
    }

    /// Resolve the path to the lint-arwaky-mcp binary.
    fn which_mcp_binary(&self) -> McpBinaryNameVO {
        let exe_candidate = std::env::current_exe()
            .ok()
            .and_then(|p| {
                p.parent()
                    .map(|d| d.join("lint-arwaky-mcp").to_string_lossy().to_string())
            })
            .unwrap_or_default();
        let cargo_home = match std::env::var("CARGO_HOME") {
            Ok(home) => home,
            Err(_) => "~/.cargo".to_string(),
        };
        let candidates = [
            exe_candidate,
            format!("{}/bin/lint-arwaky-mcp", cargo_home),
            "lint-arwaky-mcp".to_string(),
        ];
        for c in &candidates {
            if !c.is_empty() && std::path::Path::new(c).exists() {
                return McpBinaryNameVO::new(c.clone());
            }
        }
        let which_output = if let Ok(path) = std::env::var("PATH") {
            path.split(':')
                .map(|p| std::path::Path::new(p).join("lint-arwaky-mcp"))
                .find(|p| p.is_file())
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_else(|| "lint-arwaky-mcp".to_string())
        } else {
            "lint-arwaky-mcp".to_string()
        };
        McpBinaryNameVO::new(which_output)
    }

    fn install_python_adapters(&self) -> SuccessStatus {
        let res = self.installer.install_python_packages(&[
            "ruff".to_string(),
            "mypy".to_string(),
            "bandit".to_string(),
        ]);
        SuccessStatus::new(res.is_ok())
    }

    fn install_javascript_adapters(&self, sudo: bool) -> SuccessStatus {
        let res = self.installer.install_npm_packages(
            &[
                "eslint".to_string(),
                "prettier".to_string(),
                "typescript".to_string(),
            ],
            sudo,
        );
        SuccessStatus::new(res.is_ok())
    }

    fn detect_language(&self) -> ProjectLanguageVO {
        let langs = self.detect_languages();
        langs
            .values
            .into_iter()
            .next()
            .unwrap_or_else(|| ProjectLanguageVO::new("rust"))
    }

    fn detect_languages(&self) -> ProjectLanguagesVO {
        let mut found_rust = false;
        let mut found_python = false;
        let mut found_javascript = false;

        // Phase 1: Marker-based detection (fast, no filesystem scan)
        if std::path::Path::new("crates").exists() || std::path::Path::new("Cargo.toml").exists() {
            found_rust = true;
        }
        if std::path::Path::new("packages").exists()
            || std::path::Path::new("modules").exists()
            || std::path::Path::new("pyproject.toml").exists()
            || std::path::Path::new("setup.py").exists()
            || std::path::Path::new("requirements.txt").exists()
        {
            found_python = true;
        }
        if std::path::Path::new("package.json").exists()
            || std::path::Path::new("tsconfig.json").exists()
        {
            found_javascript = true;
        }

        // Phase 2: File-extension scan (shallow, depth-limited)
        if !(found_rust && found_python && found_javascript) {
            self.scan_source_extensions(
                std::path::Path::new("."),
                0,
                4,
                &mut found_rust,
                &mut found_python,
                &mut found_javascript,
            );
        }

        let mut langs = Vec::new();
        if found_rust {
            langs.push(ProjectLanguageVO::new("rust"));
        }
        if found_python {
            langs.push(ProjectLanguageVO::new("python"));
        }
        if found_javascript {
            langs.push(ProjectLanguageVO::new("javascript"));
        }
        if langs.is_empty() {
            langs.push(ProjectLanguageVO::new("rust"));
        }
        ProjectLanguagesVO::new(langs)
    }

    fn get_config_template(&self, language: &str) -> &'static str {
        match language {
            "rust" => include_str!("../../shared/config/lint_arwaky.config.rust.yaml"),
            "python" => include_str!("../../shared/config/lint_arwaky.config.python.yaml"),
            "javascript" => include_str!("../../shared/config/lint_arwaky.config.javascript.yaml"),
            _ => include_str!("../../shared/config/lint_arwaky.config.rust.yaml"),
        }
    }

    fn write_config_file(&self, filename: &str, content: &str) -> WriteConfigResult {
        self.filesystem
            .write_string(std::path::Path::new(filename), content)
            .map_err(|e| SetupError::io(e.to_string()))?;
        Ok(DescriptionVO::new(format!(
            "wrote {} ({} bytes)",
            filename,
            content.len()
        )))
    }

    fn create_global_config_dir(&self) -> CreateConfigDirResult {
        let config_dir = dirs::config_dir()
            .map(|d| d.join("lint-arwaky"))
            .ok_or_else(|| SetupError::invalid_state("Could not determine XDG config directory"))?;
        self.filesystem
            .create_dir_all(&config_dir)
            .map_err(|e| SetupError::io(e.to_string()))?;
        Ok(config_dir)
    }

    fn file_exists(&self, path: &str) -> bool {
        std::path::Path::new(path).exists()
    }
}

// ─── Block 3: Constructors, Helpers, Private Methods ──────

impl SetupManagementProcessor {
    pub fn new(
        installer: Arc<dyn shared::project_setup::ISetupInstallerProtocol>,
        filesystem: Arc<dyn IFilesystemAggregate>,
    ) -> Self {
        Self {
            installer,
            filesystem,
        }
    }

    /// Walk the directory tree (depth-limited) looking for source file extensions.
    /// Sets the corresponding `found_*` flag to `true` when a match is found.
    /// Skips hidden dirs, `target/`, `node_modules/`, and `vendor/` for speed.
    fn scan_source_extensions(
        &self,
        dir: &std::path::Path,
        depth: usize,
        max_depth: usize,
        found_rust: &mut bool,
        found_python: &mut bool,
        found_javascript: &mut bool,
    ) {
        if depth > max_depth {
            return;
        }
        let entries = match self.filesystem.read_dir_entries_as_pathbuf(dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for path in entries {
            if path.is_dir() {
                let name = match path.file_name().and_then(|n| n.to_str()) {
                    Some(n) => n,
                    None => continue,
                };
                if name.starts_with('.')
                    || name == "target"
                    || name == "node_modules"
                    || name == "vendor"
                    || name == "dist"
                    || name == "build"
                    || name == "__pycache__"
                {
                    continue;
                }
                self.scan_source_extensions(
                    &path,
                    depth + 1,
                    max_depth,
                    found_rust,
                    found_python,
                    found_javascript,
                );
                if *found_rust && *found_python && *found_javascript {
                    return;
                }
            } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                match ext {
                    "rs" => *found_rust = true,
                    "py" => *found_python = true,
                    "ts" | "tsx" | "mts" | "cts" | "js" | "jsx" | "mjs" | "cjs" => {
                        *found_javascript = true
                    }
                    _ => {}
                }
                if *found_rust && *found_python && *found_javascript {
                    return;
                }
            }
        }
    }
}
