// PURPOSE: SetupProcessor — processes project setup steps (env, gitignore, config, hooks)
//
// Implements ISetupManagementProtocol — the capabilities layer for project initialization.
// Handles:
//   - Environment file generation (.env with PHANTOM_ROOT for JS tools)
//   - MCP configuration generation in 3 formats (Claude, Hermes VS Code)
//   - Binary discovery for lint-arwaky-mcp (current exe dir, CARGO_HOME, PATH)
//   - Python and npm adapter installation (via ISetupInstallerProtocol with retry logic)
//   - Language detection (rust crates/, python pyproject.toml, js package.json)
//   - Config file template loading from embedded YAML files
//   - XDG config directory creation

use std::collections::HashMap;

use shared::common::taxonomy_path_vo::DirectoryPath;
use shared::mcp_server::taxonomy_job_vo::{EnvContentVO, McpConfigVO};
use shared::project_setup::contract_setup_protocol::ISetupManagementProtocol;
use shared::project_setup::taxonomy_setup_contract_vo::{
    McpBinaryNameVO, ProjectLanguageVO, ProjectLanguagesVO, SetupError,
};
use shared::taxonomy_suggestion_vo::DescriptionVO;

use shared::mcp_server::taxonomy_job_vo::SuccessStatus;
use shared::project_setup::contract_setup_protocol::ISetupInstallerProtocol;
use std::sync::Arc;

/// Business logic for generating setup and configuration artifacts.
pub struct SetupManagementProcessor {
    installer: Arc<dyn ISetupInstallerProtocol>,
}

impl SetupManagementProcessor {
    pub fn new(installer: Arc<dyn ISetupInstallerProtocol>) -> Self {
        Self { installer }
    }
}

#[async_trait::async_trait]
impl ISetupManagementProtocol for SetupManagementProcessor {
    /// Generate .env content for the lint-arwaky environment.
    fn generate_env(&self, home: &DirectoryPath) -> EnvContentVO {
        let lines = [
            "# Lint Arwaky Environment Configuration".to_string(),
            "# Generated by: lint-arwaky init".to_string(),
            "".to_string(),
            "# Phantom root (for JS/TS linters):".to_string(),
            format!("PHANTOM_ROOT={}/", home.value),
        ];
        EnvContentVO::new(lines.join("\n") + "\n")
    }

    /// Generate the base mcp.json entry for lint-arwaky.
    fn generate_mcp_config(&self) -> McpConfigVO {
        let mut config = HashMap::new();
        let server_entry = serde_json::json!({
            "command": "lint-arwaky",
            "args": [],
            "alwaysAllow": ["lint", "execute_command", "health_check", "list_commands", "read_skill_context"]
        });
        config.insert("lint-arwaky".to_string(), server_entry);
        McpConfigVO::new(config)
    }

    /// Generate Claude Desktop MCP config format.
    fn mcp_config_claude(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert("mcpServers".to_string(), serde_json::json!(base.value()));
        McpConfigVO::new(config)
    }

    /// Generate Hermes/Antigravity MCP config format.
    fn mcp_config_hermes(&self) -> McpConfigVO {
        self.generate_mcp_config()
    }

    /// Generate VS Code MCP config format.
    fn mcp_config_vscode(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert(
            "mcp".to_string(),
            serde_json::json!({"servers": base.value()}),
        );
        McpConfigVO::new(config)
    }

    /// Resolve the path to the lint-arwaky-mcp binary.
    fn which_mcp_binary(&self) -> McpBinaryNameVO {
        let exe_candidate = std::env::current_exe()
            .ok()
            .and_then(|p| {
                p.parent()
                    .map(|d| d.join("lint-arwaky-mcp").to_string_lossy().to_string())
            })
            .unwrap_or_default();
        let cargo_home = match std::env::var("CARGO_HOME") {
            Ok(home) => home,
            Err(_) => "~/.cargo".to_string(),
        };
        let candidates = [
            exe_candidate,
            format!("{}/bin/lint-arwaky-mcp", cargo_home),
            "lint-arwaky-mcp".to_string(),
        ];
        for c in &candidates {
            if !c.is_empty() && std::path::Path::new(c).exists() {
                return McpBinaryNameVO::new(c.clone());
            }
        }
        let which_output = match std::process::Command::new("which")
            .arg("lint-arwaky-mcp")
            .output()
            .ok()
            .and_then(|o| {
                if o.status.success() {
                    Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
                } else {
                    None
                }
            }) {
            Some(output) => output,
            None => "lint-arwaky-mcp".to_string(),
        };
        McpBinaryNameVO::new(which_output)
    }

    async fn install_python_adapters(&self) -> SuccessStatus {
        let res = self
            .installer
            .install_python_packages(&[
                "ruff".to_string(),
                "mypy".to_string(),
                "bandit".to_string(),
            ])
            .await;
        SuccessStatus::new(res.is_ok())
    }

    async fn install_javascript_adapters(&self, sudo: bool) -> SuccessStatus {
        let res = self
            .installer
            .install_npm_packages(
                &[
                    "eslint".to_string(),
                    "prettier".to_string(),
                    "typescript".to_string(),
                ],
                sudo,
            )
            .await;
        SuccessStatus::new(res.is_ok())
    }

    fn detect_language(&self) -> ProjectLanguageVO {
        let langs = self.detect_languages();
        langs
            .values
            .into_iter()
            .next()
            .unwrap_or_else(|| ProjectLanguageVO::new("rust"))
    }

    fn detect_languages(&self) -> ProjectLanguagesVO {
        let mut found_rust = false;
        let mut found_python = false;
        let mut found_javascript = false;

        // Phase 1: Marker-based detection (fast, no filesystem scan)
        if std::path::Path::new("crates").exists() || std::path::Path::new("Cargo.toml").exists() {
            found_rust = true;
        }
        if std::path::Path::new("packages").exists()
            || std::path::Path::new("modules").exists()
            || std::path::Path::new("pyproject.toml").exists()
            || std::path::Path::new("setup.py").exists()
            || std::path::Path::new("requirements.txt").exists()
        {
            found_python = true;
        }
        if std::path::Path::new("package.json").exists()
            || std::path::Path::new("tsconfig.json").exists()
        {
            found_javascript = true;
        }

        // Phase 2: File-extension scan (shallow, depth-limited)
        if !(found_rust && found_python && found_javascript) {
            self.scan_source_extensions(
                std::path::Path::new("."),
                0,
                4,
                &mut found_rust,
                &mut found_python,
                &mut found_javascript,
            );
        }

        let mut langs = Vec::new();
        if found_rust {
            langs.push(ProjectLanguageVO::new("rust"));
        }
        if found_python {
            langs.push(ProjectLanguageVO::new("python"));
        }
        if found_javascript {
            langs.push(ProjectLanguageVO::new("javascript"));
        }
        if langs.is_empty() {
            langs.push(ProjectLanguageVO::new("rust"));
        }
        ProjectLanguagesVO::new(langs)
    }

    fn get_config_template(&self, language: &str) -> &'static str {
        match language {
            "rust" => include_str!("../../../lint_arwaky.config.rust.yaml"),
            "python" => include_str!("../../../lint_arwaky.config.python.yaml"),
            "javascript" => include_str!("../../../lint_arwaky.config.javascript.yaml"),
            _ => include_str!("../../../lint_arwaky.config.rust.yaml"),
        }
    }

    fn write_config_file(
        &self,
        filename: &str,
        content: &str,
    ) -> Result<DescriptionVO, SetupError> {
        std::fs::write(filename, content).map_err(|e| SetupError::io(e.to_string()))?;
        Ok(DescriptionVO::new(format!(
            "wrote {} ({} bytes)",
            filename,
            content.len()
        )))
    }

    fn create_global_config_dir(&self) -> Result<std::path::PathBuf, SetupError> {
        let config_dir = dirs::config_dir()
            .map(|d| d.join("lint-arwaky"))
            .ok_or_else(|| SetupError::invalid_state("Could not determine XDG config directory"))?;
        std::fs::create_dir_all(&config_dir).map_err(|e| SetupError::io(e.to_string()))?;
        Ok(config_dir)
    }

    fn file_exists(&self, path: &str) -> bool {
        std::path::Path::new(path).exists()
    }
}

impl SetupManagementProcessor {
    /// Walk the directory tree (depth-limited) looking for source file extensions.
    /// Sets the corresponding `found_*` flag to `true` when a match is found.
    /// Skips hidden dirs, `target/`, `node_modules/`, and `vendor/` for speed.
    fn scan_source_extensions(
        &self,
        dir: &std::path::Path,
        depth: usize,
        max_depth: usize,
        found_rust: &mut bool,
        found_python: &mut bool,
        found_javascript: &mut bool,
    ) {
        if depth > max_depth {
            return;
        }
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let name = path.file_name().unwrap_or_default().to_string_lossy();
                if name.starts_with('.')
                    || name == "target"
                    || name == "node_modules"
                    || name == "vendor"
                    || name == "dist"
                    || name == "build"
                    || name == "__pycache__"
                {
                    continue;
                }
                self.scan_source_extensions(
                    &path,
                    depth + 1,
                    max_depth,
                    found_rust,
                    found_python,
                    found_javascript,
                );
                if *found_rust && *found_python && *found_javascript {
                    return;
                }
            } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                match ext {
                    "rs" => *found_rust = true,
                    "py" => *found_python = true,
                    "ts" | "tsx" | "mts" | "cts" | "js" | "jsx" | "mjs" | "cjs" => {
                        *found_javascript = true
                    }
                    _ => {}
                }
                if *found_rust && *found_python && *found_javascript {
                    return;
                }
            }
        }
    }
}
