// PURPOSE: SetupEnvGenerator — capability for environment file generation
//
// Implements IEnvGenerationProtocol. Generates .env content with PHANTOM_ROOT
// for JS/TS IDE integration during project initialization.

use shared_common::taxonomy_job_vo::EnvContentVO;
use shared_common::taxonomy_path_vo::DirectoryPath;
use shared_filesystem::contract_filesystem_protocol::IFileSystemIOProtocol;
use shared_project_setup::contract_setup_protocol::IEnvGenerationProtocol;

use std::sync::Arc;

// ─── Block 1: Struct Definition ───────────────────────────

/// Business logic for environment file generation.
pub struct SetupEnvGenerator {
    io: Arc<dyn IFileSystemIOProtocol>,
}

// ─── Block 2: Protocol Trait Implementation ───────────────

impl IEnvGenerationProtocol for SetupEnvGenerator {
    /// Generate .env content for the lint-arwaky environment.
    fn generate_env(&self, home: &DirectoryPath) -> EnvContentVO {
        let _ = self.io.create_dir_all(std::path::Path::new(&home.value));
        let lines = [
            "# Lint Arwaky Environment Configuration".to_string(),
            "# Generated by: lint-arwaky init".to_string(),
            "".to_string(),
            "# Phantom root (for JS/TS linters):".to_string(),
            format!("PHANTOM_ROOT={}/", home.value),
        ];
        EnvContentVO::new(lines.join("\n") + "\n")
    }
}

// ─── Block 3: Constructors ────────────────────────────────

impl SetupEnvGenerator {
    pub fn new(io: Arc<dyn IFileSystemIOProtocol>) -> Self {
        Self { io }
    }
}
