// PURPOSE: SetupProcessor — processes project setup steps (env, gitignore, config, hooks)

use std::collections::HashMap;

use shared::mcp_server::taxonomy_job_vo::{EnvContentVO, McpConfigVO};
use shared::project_setup::contract_setup_protocol::ISetupManagementProtocol;
use shared::source_parsing::taxonomy_path_vo::DirectoryPath;

use shared::mcp_server::taxonomy_job_vo::SuccessStatus;
use shared::project_setup::contract_setup_protocol::ISetupInstallerPort;
use std::sync::Arc;

/// Business logic for generating setup and configuration artifacts.
pub struct SetupManagementProcessor {
    installer: Arc<dyn ISetupInstallerPort>,
}

impl SetupManagementProcessor {
    pub fn new(installer: Arc<dyn ISetupInstallerPort>) -> Self {
        Self { installer }
    }
}

#[async_trait::async_trait]
impl ISetupManagementProtocol for SetupManagementProcessor {
    /// Generate .env content for the lint-arwaky environment.
    fn generate_env(&self, home: &DirectoryPath) -> EnvContentVO {
        let lines = [
            "# Lint Arwaky Environment Configuration".to_string(),
            "# Generated by: lint-arwaky init".to_string(),
            "".to_string(),
            "# Phantom root (for JS/TS linters):".to_string(),
            format!("PHANTOM_ROOT={}/", home.value),
        ];
        EnvContentVO::new(lines.join("\n") + "\n")
    }

    /// Generate the base mcp.json entry for lint-arwaky.
    fn generate_mcp_config(&self) -> McpConfigVO {
        let mut config = HashMap::new();
        let server_entry = serde_json::json!({
            "command": "lint-arwaky",
            "args": [],
            "alwaysAllow": ["lint", "execute_command", "health_check", "list_commands", "read_skill_context"]
        });
        config.insert("lint-arwaky".to_string(), server_entry);
        McpConfigVO::new(config)
    }

    /// Generate Claude Desktop MCP config format.
    fn mcp_config_claude(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert("mcpServers".to_string(), serde_json::json!(base.value()));
        McpConfigVO::new(config)
    }

    /// Generate Hermes/Antigravity MCP config format.
    fn mcp_config_hermes(&self) -> McpConfigVO {
        self.generate_mcp_config()
    }

    /// Generate VS Code MCP config format.
    fn mcp_config_vscode(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert(
            "mcp".to_string(),
            serde_json::json!({"servers": base.value()}),
        );
        McpConfigVO::new(config)
    }

    /// Resolve the path to the lint-arwaky-mcp binary.
    fn which_mcp_binary(&self) -> String {
        let candidates = [
            std::env::current_exe()
                .ok()
                .and_then(|p| {
                    p.parent()
                        .map(|d| d.join("lint-arwaky-mcp").to_string_lossy().to_string())
                })
                .unwrap_or_default(),
            format!(
                "{}/bin/lint-arwaky-mcp",
                std::env::var("CARGO_HOME").unwrap_or_else(|_| "~/.cargo".to_string())
            ),
            "lint-arwaky-mcp".to_string(),
        ];
        for c in &candidates {
            if !c.is_empty() && std::path::Path::new(c).exists() {
                return c.clone();
            }
        }
        std::process::Command::new("which")
            .arg("lint-arwaky-mcp")
            .output()
            .ok()
            .and_then(|o| {
                if o.status.success() {
                    Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
                } else {
                    None
                }
            })
            .unwrap_or_else(|| "lint-arwaky-mcp".to_string())
    }

    async fn install_python_adapters(&self) -> SuccessStatus {
        let res = self
            .installer
            .install_python_packages(&[
                "ruff".to_string(),
                "mypy".to_string(),
                "bandit".to_string(),
            ])
            .await;
        SuccessStatus::new(res.is_ok())
    }

    async fn install_javascript_adapters(&self, sudo: bool) -> SuccessStatus {
        let res = self
            .installer
            .install_npm_packages(
                &[
                    "eslint".to_string(),
                    "prettier".to_string(),
                    "typescript".to_string(),
                ],
                sudo,
            )
            .await;
        SuccessStatus::new(res.is_ok())
    }
}
