// PURPOSE: build script — emit the release version into OUT_DIR.
//
// Every crate that prints a version used to reach for `CARGO_PKG_VERSION`,
// which resolves to *that crate's* package version, not the binary's. The
// consequence was that the tool reported different versions depending on
// which code path printed: `la version` came from `dispatcher` (3.7.2)
// while the scan header came from `shared/cli_commands` (0.1.0). A release
// bump that moved only the root `Cargo.toml` shipped a binary still
// announcing the previous release.
//
// The fix is one committed file, `VERSION` at the workspace root, read here
// and handed to the rest of the workspace through `OUT_DIR`. `shared-common`
// owns the build script because every crate that prints a version already
// depends on it.
//
// Failures print and exit rather than unwinding, matching `crates/shared/build.rs`
// — a build script has no caller to return an error to, and AES304 forbids the
// `expect`/`panic!` forms.

use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(v) => v,
        Err(e) => fail(&format!("CARGO_MANIFEST_DIR not set: {e}")),
    };
    let out_dir = match std::env::var("OUT_DIR") {
        Ok(v) => v,
        Err(e) => fail(&format!("OUT_DIR not set: {e}")),
    };

    let version_file = match find_version_file(Path::new(&manifest_dir)) {
        Some(p) => p,
        None => fail(&format!("no VERSION file at or above {}", manifest_dir)),
    };

    let raw = match std::fs::read_to_string(&version_file) {
        Ok(v) => v,
        Err(e) => fail(&format!("failed to read {}: {e}", version_file.display())),
    };
    let version = raw.trim();
    if version.is_empty() {
        fail(&format!("{} is empty", version_file.display()));
    }

    let dest = PathBuf::from(&out_dir).join("release_version.rs");
    let contents = format!(
        "// Generated by crates/shared/src/common/build.rs from the workspace\n\
         // VERSION file. Do not edit.\n\
         /// The lint-arwaky release version, identical in every binary and\n\
         /// every output format.\n\
         pub const RELEASE_VERSION: &str = \"{version}\";\n"
    );
    if let Err(e) = std::fs::write(&dest, contents) {
        fail(&format!("failed to write {}: {e}", dest.display()));
    }

    // Rebuild when the version moves, or when this script changes.
    println!("cargo:rerun-if-changed={}", version_file.display());
    println!("cargo:rerun-if-changed=build.rs");
}

/// Report a build-script failure and stop. A build script cannot return an
/// error, so this is the whole error channel.
fn fail(message: &str) -> ! {
    eprintln!("build.rs: {message}");
    std::process::exit(1);
}

/// Walk up from the crate directory to the directory carrying `VERSION`.
///
/// The crate sits at `crates/shared/src/common`, so the root is three levels
/// up; the loop also covers the packaged layout, where the file is copied in
/// beside the manifest.
fn find_version_file(start: &Path) -> Option<PathBuf> {
    let mut current = Some(start);
    while let Some(dir) = current {
        let candidate = dir.join("VERSION");
        if candidate.is_file() {
            return Some(candidate);
        }
        current = dir.parent();
    }
    None
}
