// PURPOSE: PackageName — value object for package/dependency names
//
// `PackageName` wraps a String that identifies a crate (Rust), package
// (Python), or npm package (TypeScript). It is generated via the
// `string_value_object!` macro which supplies standard trait impls.
use crate::string_value_object;

// PackageName is a type-safe wrapper around String, generated by the
// string_value_object! macro. Package names identify crates (Rust),
// packages (Python), or npm packages (TypeScript) across the codebase.
string_value_object!(PackageName);
