// PURPOSE: GitBranchName — value object for git branch identifiers
//
// This value object wraps a String that represents a Git branch name.
// It is generated via the `string_value_object!` macro which provides
// basic equality, display, and conversion traits out of the box.
use crate::string_value_object;

// GitBranchName is a type-safe wrapper around String, generated by the
// string_value_object! macro. Branch names are used throughout the hook
// and watch systems to identify Git branches without raw string types.
string_value_object!(GitBranchName);
