// PURPOSE: utility_release_version — the one version string every binary prints.
//
// Utility: a single constant, no state, no types (AES404).
//
// `RELEASE_VERSION` is generated by this crate's `build.rs` from the `VERSION`
// file at the workspace root. It replaces `env!("CARGO_PKG_VERSION")`, which
// resolved to whichever crate happened to contain the printing code — so
// `la version` reported the dispatcher's package version while the scan header
// reported `cli_commands`'s, and a release bump that moved only the root
// `Cargo.toml` shipped a binary announcing the previous release.

include!(concat!(env!("OUT_DIR"), "/release_version.rs"));
