[package]
name = "config-system-lint-arwaky"
version = "3.6.1"
edition = "2024"
description = "Configuration loading, parsing, validation, and workspace detection. Resolves `lint_arwaky.config.*.yaml` and merges it with project-level overrides."
license = "MIT"
repository = "https://github.com/rakaarwaky/lint-arwaky"
publish = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
toml.workspace = true
shared.workspace = true
dirs.workspace = true
dashmap = "6"
tracing.workspace = true

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
tempfile = "3"
filesystem.workspace = true

[[bench]]
name = "bench_config_system"
path = "benches/bench_config_system.rs"
harness = false
