// AES406: surface with too many control flow statements
function handler(): void {
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
    if (true) {} else {}
}
