// PURPOSE: Embedded skills constants compiled directly into binary
use crate::taxonomy_project_setup_vo::EmbeddedSkillVO;

/// All embedded skills compiled into the binary for initialization.
///
/// Each skill ships a language-agnostic `SKILL.md` (always installed)
/// plus optional language-specific `reference(s)/<HOW-TO-*.md>` files
/// that are installed only when that language is detected.
///
/// The markdown source of truth lives in `crates/shared/skills/`. `build.rs`
/// copies it into OUT_DIR so `include_str!` picks up changes at compile time;
/// `[package] include` ships the same source in the published crate.
/// Regenerate this constant with `python3 tools/regenerate_skills.py` after
/// adding, removing, or renaming a skill file.
pub const EMBEDDED_SKILLS_COUNT: usize = 56;

pub const EMBEDDED_SKILLS: &[EmbeddedSkillVO] = &[
    EmbeddedSkillVO::new(
        "README",
        "README.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/README.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-agent",
        "aes-agent/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-agent/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-agent",
        "aes-agent/references/HOW-TO-MAKE-PYTHON-AGENT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-agent/references/HOW-TO-MAKE-PYTHON-AGENT.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-agent",
        "aes-agent/references/HOW-TO-MAKE-RUST-AGENT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-agent/references/HOW-TO-MAKE-RUST-AGENT.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-agent",
        "aes-agent/references/HOW-TO-MAKE-TYPESCRIPT-AGENT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-agent/references/HOW-TO-MAKE-TYPESCRIPT-AGENT.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-capabilities",
        "aes-capabilities/SKILL.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-capabilities/SKILL.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-capabilities",
        "aes-capabilities/references/HOW-TO-MAKE-PYTHON-CAPABILITIES.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-capabilities/references/HOW-TO-MAKE-PYTHON-CAPABILITIES.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-capabilities",
        "aes-capabilities/references/HOW-TO-MAKE-RUST-CAPABILITIES.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-capabilities/references/HOW-TO-MAKE-RUST-CAPABILITIES.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-capabilities",
        "aes-capabilities/references/HOW-TO-MAKE-TYPESCRIPT-CAPABILITIES.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-capabilities/references/HOW-TO-MAKE-TYPESCRIPT-CAPABILITIES.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-contract",
        "aes-contract/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-contract/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-contract",
        "aes-contract/references/HOW-TO-MAKE-PYTHON-CONTRACT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-contract/references/HOW-TO-MAKE-PYTHON-CONTRACT.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-contract",
        "aes-contract/references/HOW-TO-MAKE-RUST-CONTRACT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-contract/references/HOW-TO-MAKE-RUST-CONTRACT.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-contract",
        "aes-contract/references/HOW-TO-MAKE-TYPESCRIPT-CONTRACT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-contract/references/HOW-TO-MAKE-TYPESCRIPT-CONTRACT.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-docs/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-AGENTS.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-AGENTS.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-ARCHITECTURE.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-ARCHITECTURE.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-BACKLOG.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-BACKLOG.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-CONTRIBUTING.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-CONTRIBUTING.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-DESIGN.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-DESIGN.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-FRD.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-FRD.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-PRD.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-PRD.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-PYTHON-DOC.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-PYTHON-DOC.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-README.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-README.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-ROADMAP.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-ROADMAP.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-RUST-DOC.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-RUST-DOC.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-docs",
        "aes-docs/references/HOW-TO-MAKE-TYPESCRIPT-DOC.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-docs/references/HOW-TO-MAKE-TYPESCRIPT-DOC.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-lint-arwaky",
        "aes-lint-arwaky/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-lint-arwaky/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-lint-arwaky",
        "aes-lint-arwaky/references/HOW-TO-USE-LINT-COMMANDS.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-lint-arwaky/references/HOW-TO-USE-LINT-COMMANDS.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-lint-arwaky",
        "aes-lint-arwaky/references/HOW-TO-USE-LINT-PYTHON.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-lint-arwaky/references/HOW-TO-USE-LINT-PYTHON.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-lint-arwaky",
        "aes-lint-arwaky/references/HOW-TO-USE-LINT-ROUTING.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-lint-arwaky/references/HOW-TO-USE-LINT-ROUTING.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-lint-arwaky",
        "aes-lint-arwaky/references/HOW-TO-USE-LINT-RUST.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-lint-arwaky/references/HOW-TO-USE-LINT-RUST.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-lint-arwaky",
        "aes-lint-arwaky/references/HOW-TO-USE-LINT-TYPESCRIPT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-lint-arwaky/references/HOW-TO-USE-LINT-TYPESCRIPT.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-migration",
        "aes-migration/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-migration/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-migration",
        "aes-migration/reference/HOW-TO-MAKE-PYTHON-MIGRATION.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-migration/reference/HOW-TO-MAKE-PYTHON-MIGRATION.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-migration",
        "aes-migration/reference/HOW-TO-MAKE-RUST-MIGRATION.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-migration/reference/HOW-TO-MAKE-RUST-MIGRATION.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-migration",
        "aes-migration/reference/HOW-TO-MAKE-TYPESCRIPT-MIGRATION.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-migration/reference/HOW-TO-MAKE-TYPESCRIPT-MIGRATION.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-root",
        "aes-root/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-root/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-root",
        "aes-root/references/HOW-TO-MAKE-PYTHON-ROOT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-root/references/HOW-TO-MAKE-PYTHON-ROOT.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-root",
        "aes-root/references/HOW-TO-MAKE-RUST-ROOT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-root/references/HOW-TO-MAKE-RUST-ROOT.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-root",
        "aes-root/references/HOW-TO-MAKE-TYPESCRIPT-ROOT.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-root/references/HOW-TO-MAKE-TYPESCRIPT-ROOT.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-surface",
        "aes-surface/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-surface/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-surface",
        "aes-surface/references/HOW-TO-MAKE-PYTHON-SURFACE.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-surface/references/HOW-TO-MAKE-PYTHON-SURFACE.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-surface",
        "aes-surface/references/HOW-TO-MAKE-RUST-SURFACE.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-surface/references/HOW-TO-MAKE-RUST-SURFACE.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-surface",
        "aes-surface/references/HOW-TO-MAKE-TYPESCRIPT-SURFACE.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-surface/references/HOW-TO-MAKE-TYPESCRIPT-SURFACE.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-taxonomy",
        "aes-taxonomy/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-taxonomy/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-taxonomy",
        "aes-taxonomy/references/HOW-TO-MAKE-PYTHON-TAXONOMY.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-taxonomy/references/HOW-TO-MAKE-PYTHON-TAXONOMY.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-taxonomy",
        "aes-taxonomy/references/HOW-TO-MAKE-RUST-TAXONOMY.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-taxonomy/references/HOW-TO-MAKE-RUST-TAXONOMY.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-taxonomy",
        "aes-taxonomy/references/HOW-TO-MAKE-TYPESCRIPT-TAXONOMY.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-taxonomy/references/HOW-TO-MAKE-TYPESCRIPT-TAXONOMY.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-testing-suite",
        "aes-testing-suite/SKILL.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-testing-suite/SKILL.md"
        )),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-testing-suite",
        "aes-testing-suite/references/HOW-TO-MAKE-PYTHON-TESTING.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-testing-suite/references/HOW-TO-MAKE-PYTHON-TESTING.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-testing-suite",
        "aes-testing-suite/references/HOW-TO-MAKE-RUST-TESTING.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-testing-suite/references/HOW-TO-MAKE-RUST-TESTING.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-testing-suite",
        "aes-testing-suite/references/HOW-TO-MAKE-TYPESCRIPT-TESTING.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-testing-suite/references/HOW-TO-MAKE-TYPESCRIPT-TESTING.md"
        )),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "aes-utility",
        "aes-utility/SKILL.md",
        include_str!(concat!(env!("OUT_DIR"), "/skills/aes-utility/SKILL.md")),
        None,
    ),
    EmbeddedSkillVO::new(
        "aes-utility",
        "aes-utility/references/HOW-TO-MAKE-PYTHON-UTILITY.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-utility/references/HOW-TO-MAKE-PYTHON-UTILITY.md"
        )),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "aes-utility",
        "aes-utility/references/HOW-TO-MAKE-RUST-UTILITY.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-utility/references/HOW-TO-MAKE-RUST-UTILITY.md"
        )),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "aes-utility",
        "aes-utility/references/HOW-TO-MAKE-TYPESCRIPT-UTILITY.md",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/skills/aes-utility/references/HOW-TO-MAKE-TYPESCRIPT-UTILITY.md"
        )),
        Some("typescript"),
    ),
];
