// PURPOSE: Embedded skills constants compiled directly into binary
use crate::project_setup::taxonomy_skills_vo::EmbeddedSkillVO;

/// All embedded skills compiled into the binary for initialization.
///
/// Each consolidated skill ships one language-agnostic `SKILL.md` (`language: None`,
/// always installed) plus optional `references/<language>.md` halves that carry the
/// per-language detail and are installed only when that language is detected.
/// The markdown source of truth lives in `crates/skills/` — edit the files
/// directly there; `include_str!` picks up changes at compile time.
pub const EMBEDDED_SKILLS: &[EmbeddedSkillVO] = &[
    EmbeddedSkillVO::new(
        "README.md",
        "README.md",
        include_str!("../../../skills/README.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "add-docs",
        "add-docs/SKILL.md",
        include_str!("../../../skills/add-docs/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "author-skill-md",
        "author-skill-md/SKILL.md",
        include_str!("../../../skills/author-skill-md/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "author-skill-md-hermes-upstream-repo",
        "author-skill-md/references/hermes-upstream-repo.md",
        include_str!("../../../skills/author-skill-md/references/hermes-upstream-repo.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "cleanup-consolidate",
        "cleanup-consolidate/SKILL.md",
        include_str!("../../../skills/cleanup-consolidate/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "cleanup-consolidate-python",
        "cleanup-consolidate/references/python.md",
        include_str!("../../../skills/cleanup-consolidate/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "cleanup-consolidate-rust",
        "cleanup-consolidate/references/rust.md",
        include_str!("../../../skills/cleanup-consolidate/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "cleanup-consolidate-typescript",
        "cleanup-consolidate/references/typescript.md",
        include_str!("../../../skills/cleanup-consolidate/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "create-agent",
        "create-agent/SKILL.md",
        include_str!("../../../skills/create-agent/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "create-agent-python",
        "create-agent/references/python.md",
        include_str!("../../../skills/create-agent/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "create-agent-rust",
        "create-agent/references/rust.md",
        include_str!("../../../skills/create-agent/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "create-agent-typescript",
        "create-agent/references/typescript.md",
        include_str!("../../../skills/create-agent/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "create-capabilities",
        "create-capabilities/SKILL.md",
        include_str!("../../../skills/create-capabilities/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "create-capabilities-python",
        "create-capabilities/references/python.md",
        include_str!("../../../skills/create-capabilities/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "create-capabilities-rust",
        "create-capabilities/references/rust.md",
        include_str!("../../../skills/create-capabilities/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "create-capabilities-typescript",
        "create-capabilities/references/typescript.md",
        include_str!("../../../skills/create-capabilities/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "create-contract",
        "create-contract/SKILL.md",
        include_str!("../../../skills/create-contract/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "create-contract-python",
        "create-contract/references/python.md",
        include_str!("../../../skills/create-contract/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "create-contract-rust",
        "create-contract/references/rust.md",
        include_str!("../../../skills/create-contract/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "create-contract-typescript",
        "create-contract/references/typescript.md",
        include_str!("../../../skills/create-contract/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "create-root",
        "create-root/SKILL.md",
        include_str!("../../../skills/create-root/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "create-root-python",
        "create-root/references/python.md",
        include_str!("../../../skills/create-root/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "create-root-rust",
        "create-root/references/rust.md",
        include_str!("../../../skills/create-root/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "create-root-typescript",
        "create-root/references/typescript.md",
        include_str!("../../../skills/create-root/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "create-surface",
        "create-surface/SKILL.md",
        include_str!("../../../skills/create-surface/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "create-surface-python",
        "create-surface/references/python.md",
        include_str!("../../../skills/create-surface/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "create-surface-rust",
        "create-surface/references/rust.md",
        include_str!("../../../skills/create-surface/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "create-surface-typescript",
        "create-surface/references/typescript.md",
        include_str!("../../../skills/create-surface/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "create-taxonomy",
        "create-taxonomy/SKILL.md",
        include_str!("../../../skills/create-taxonomy/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "create-taxonomy-python",
        "create-taxonomy/references/python.md",
        include_str!("../../../skills/create-taxonomy/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "create-taxonomy-rust",
        "create-taxonomy/references/rust.md",
        include_str!("../../../skills/create-taxonomy/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "create-taxonomy-typescript",
        "create-taxonomy/references/typescript.md",
        include_str!("../../../skills/create-taxonomy/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "create-utility",
        "create-utility/SKILL.md",
        include_str!("../../../skills/create-utility/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "create-utility-python",
        "create-utility/references/python.md",
        include_str!("../../../skills/create-utility/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "create-utility-rust",
        "create-utility/references/rust.md",
        include_str!("../../../skills/create-utility/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "create-utility-typescript",
        "create-utility/references/typescript.md",
        include_str!("../../../skills/create-utility/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "fix-bypass",
        "fix-bypass/SKILL.md",
        include_str!("../../../skills/fix-bypass/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "lint-arwaky",
        "lint-arwaky/SKILL.md",
        include_str!("../../../skills/lint-arwaky/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "lint-arwaky-python",
        "lint-arwaky/references/python.md",
        include_str!("../../../skills/lint-arwaky/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "lint-arwaky-rule-routing",
        "lint-arwaky/references/rule-routing.md",
        include_str!("../../../skills/lint-arwaky/references/rule-routing.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "lint-arwaky-rust",
        "lint-arwaky/references/rust.md",
        include_str!("../../../skills/lint-arwaky/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "lint-arwaky-typescript",
        "lint-arwaky/references/typescript.md",
        include_str!("../../../skills/lint-arwaky/references/typescript.md"),
        Some("typescript"),
    ),
    EmbeddedSkillVO::new(
        "setup-ci-quality-gates",
        "setup-ci-quality-gates/SKILL.md",
        include_str!("../../../skills/setup-ci-quality-gates/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "testing-suite",
        "testing-suite/SKILL.md",
        include_str!("../../../skills/testing-suite/SKILL.md"),
        None,
    ),
    EmbeddedSkillVO::new(
        "testing-suite-python",
        "testing-suite/references/python.md",
        include_str!("../../../skills/testing-suite/references/python.md"),
        Some("python"),
    ),
    EmbeddedSkillVO::new(
        "testing-suite-rust",
        "testing-suite/references/rust.md",
        include_str!("../../../skills/testing-suite/references/rust.md"),
        Some("rust"),
    ),
    EmbeddedSkillVO::new(
        "testing-suite-typescript",
        "testing-suite/references/typescript.md",
        include_str!("../../../skills/testing-suite/references/typescript.md"),
        Some("typescript"),
    ),
];
