// PURPOSE: SetupProcessor — processes project setup steps (env, gitignore, config, hooks)

use std::collections::HashMap;

use crate::pipeline_jobs::taxonomy_job_vo::{EnvContentVO, McpConfigVO};
use crate::project_setup::contract_setup_protocol::ISetupManagementProtocol;
use crate::source_parsing::taxonomy_path_vo::DirectoryPath;

/// Business logic for generating setup and configuration artifacts.
pub struct SetupManagementProcessor {}

impl Default for SetupManagementProcessor {
    fn default() -> Self {
        Self::new()
    }
}

impl SetupManagementProcessor {
    pub fn new() -> Self {
        Self {}
    }
}

impl ISetupManagementProtocol for SetupManagementProcessor {
    /// Generate .env content for the lint-arwaky environment.
    fn generate_env(&self, home: &DirectoryPath) -> EnvContentVO {
        let lines = [
            "# Lint Arwaky Environment Configuration".to_string(),
            "# Generated by: lint-arwaky init".to_string(),
            "".to_string(),
            "# Phantom root (for JS/TS linters):".to_string(),
            format!("PHANTOM_ROOT={}/", home.value),
        ];
        EnvContentVO::new(lines.join("\n") + "\n")
    }

    /// Generate the base mcp.json entry for lint-arwaky.
    fn generate_mcp_config(&self) -> McpConfigVO {
        let mut config = HashMap::new();
        let server_entry = serde_json::json!({
            "command": "lint-arwaky",
            "args": [],
            "alwaysAllow": ["lint", "execute_command", "health_check", "list_commands", "read_skill_context"]
        });
        config.insert("lint-arwaky".to_string(), server_entry);
        McpConfigVO::new(config)
    }

    /// Generate Claude Desktop MCP config format.
    fn mcp_config_claude(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert("mcpServers".to_string(), serde_json::json!(base.value()));
        McpConfigVO::new(config)
    }

    /// Generate Hermes/Antigravity MCP config format.
    fn mcp_config_hermes(&self) -> McpConfigVO {
        self.generate_mcp_config()
    }

    /// Generate VS Code MCP config format.
    fn mcp_config_vscode(&self) -> McpConfigVO {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert(
            "mcp".to_string(),
            serde_json::json!({"servers": base.value()}),
        );
        McpConfigVO::new(config)
    }
}
