# AES406: surface with too many control flow statements
def handler():
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
    if True: pass
