[package]
name = "calculator-workspace"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "calculator"
path = "crates/root_calculator_entry.rs"

[dependencies]
calculator = { path = "crates/calculator" }
calculator-cli = { path = "crates/cli" }
calculator-shared = { path = "crates/shared" }
clap = { version = "4", features = ["derive"] }

[workspace]
resolver = "2"
members = [
    "crates/shared",
    "crates/cli",
    "crates/calculator",
]
