[package]
name = "calculator-root"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "calculator"
path = "main.rs"

[dependencies]
calculator-shared = { path = "../shared" }
calculator-addition = { path = "../addition" }
calculator-subtraction = { path = "../subtraction" }
calculator-multiplication = { path = "../multiplication" }
calculator-division = { path = "../division" }
calculator-cli = { path = "../cli" }
