// line 1 - padding content for AES004 file too large violation
// line 2 - padding content for AES004 file too large violation
// line 3 - padding content for AES004 file too large violation
// line 4 - padding content for AES004 file too large violation
// line 5 - padding content for AES004 file too large violation
// line 6 - padding content for AES004 file too large violation
// line 7 - padding content for AES004 file too large violation
// line 8 - padding content for AES004 file too large violation
// line 9 - padding content for AES004 file too large violation
// line 10 - padding content for AES004 file too large violation
// line 11 - padding content for AES004 file too large violation
// line 12 - padding content for AES004 file too large violation
// line 13 - padding content for AES004 file too large violation
// line 14 - padding content for AES004 file too large violation
// line 15 - padding content for AES004 file too large violation
// line 16 - padding content for AES004 file too large violation
// line 17 - padding content for AES004 file too large violation
// line 18 - padding content for AES004 file too large violation
// line 19 - padding content for AES004 file too large violation
// line 20 - padding content for AES004 file too large violation
// line 21 - padding content for AES004 file too large violation
// line 22 - padding content for AES004 file too large violation
// line 23 - padding content for AES004 file too large violation
// line 24 - padding content for AES004 file too large violation
// line 25 - padding content for AES004 file too large violation
// line 26 - padding content for AES004 file too large violation
// line 27 - padding content for AES004 file too large violation
// line 28 - padding content for AES004 file too large violation
// line 29 - padding content for AES004 file too large violation
// line 30 - padding content for AES004 file too large violation
// line 31 - padding content for AES004 file too large violation
// line 32 - padding content for AES004 file too large violation
// line 33 - padding content for AES004 file too large violation
// line 34 - padding content for AES004 file too large violation
// line 35 - padding content for AES004 file too large violation
// line 36 - padding content for AES004 file too large violation
// line 37 - padding content for AES004 file too large violation
// line 38 - padding content for AES004 file too large violation
// line 39 - padding content for AES004 file too large violation
// line 40 - padding content for AES004 file too large violation
// line 41 - padding content for AES004 file too large violation
// line 42 - padding content for AES004 file too large violation
// line 43 - padding content for AES004 file too large violation
// line 44 - padding content for AES004 file too large violation
// line 45 - padding content for AES004 file too large violation
// line 46 - padding content for AES004 file too large violation
// line 47 - padding content for AES004 file too large violation
// line 48 - padding content for AES004 file too large violation
// line 49 - padding content for AES004 file too large violation
// line 50 - padding content for AES004 file too large violation
// line 51 - padding content for AES004 file too large violation
// line 52 - padding content for AES004 file too large violation
// line 53 - padding content for AES004 file too large violation
// line 54 - padding content for AES004 file too large violation
// line 55 - padding content for AES004 file too large violation
// line 56 - padding content for AES004 file too large violation
// line 57 - padding content for AES004 file too large violation
// line 58 - padding content for AES004 file too large violation
// line 59 - padding content for AES004 file too large violation
// line 60 - padding content for AES004 file too large violation
// line 61 - padding content for AES004 file too large violation
// line 62 - padding content for AES004 file too large violation
// line 63 - padding content for AES004 file too large violation
// line 64 - padding content for AES004 file too large violation
// line 65 - padding content for AES004 file too large violation
// line 66 - padding content for AES004 file too large violation
// line 67 - padding content for AES004 file too large violation
// line 68 - padding content for AES004 file too large violation
// line 69 - padding content for AES004 file too large violation
// line 70 - padding content for AES004 file too large violation
// line 71 - padding content for AES004 file too large violation
// line 72 - padding content for AES004 file too large violation
// line 73 - padding content for AES004 file too large violation
// line 74 - padding content for AES004 file too large violation
// line 75 - padding content for AES004 file too large violation
// line 76 - padding content for AES004 file too large violation
// line 77 - padding content for AES004 file too large violation
// line 78 - padding content for AES004 file too large violation
// line 79 - padding content for AES004 file too large violation
// line 80 - padding content for AES004 file too large violation
// line 81 - padding content for AES004 file too large violation
// line 82 - padding content for AES004 file too large violation
// line 83 - padding content for AES004 file too large violation
// line 84 - padding content for AES004 file too large violation
// line 85 - padding content for AES004 file too large violation
// line 86 - padding content for AES004 file too large violation
// line 87 - padding content for AES004 file too large violation
// line 88 - padding content for AES004 file too large violation
// line 89 - padding content for AES004 file too large violation
// line 90 - padding content for AES004 file too large violation
// line 91 - padding content for AES004 file too large violation
// line 92 - padding content for AES004 file too large violation
// line 93 - padding content for AES004 file too large violation
// line 94 - padding content for AES004 file too large violation
// line 95 - padding content for AES004 file too large violation
// line 96 - padding content for AES004 file too large violation
// line 97 - padding content for AES004 file too large violation
// line 98 - padding content for AES004 file too large violation
// line 99 - padding content for AES004 file too large violation
// line 100 - padding content for AES004 file too large violation
// line 101 - padding content for AES004 file too large violation
// line 102 - padding content for AES004 file too large violation
// line 103 - padding content for AES004 file too large violation
// line 104 - padding content for AES004 file too large violation
// line 105 - padding content for AES004 file too large violation
// line 106 - padding content for AES004 file too large violation
// line 107 - padding content for AES004 file too large violation
// line 108 - padding content for AES004 file too large violation
// line 109 - padding content for AES004 file too large violation
// line 110 - padding content for AES004 file too large violation
// line 111 - padding content for AES004 file too large violation
// line 112 - padding content for AES004 file too large violation
// line 113 - padding content for AES004 file too large violation
// line 114 - padding content for AES004 file too large violation
// line 115 - padding content for AES004 file too large violation
// line 116 - padding content for AES004 file too large violation
// line 117 - padding content for AES004 file too large violation
// line 118 - padding content for AES004 file too large violation
// line 119 - padding content for AES004 file too large violation
// line 120 - padding content for AES004 file too large violation
// line 121 - padding content for AES004 file too large violation
// line 122 - padding content for AES004 file too large violation
// line 123 - padding content for AES004 file too large violation
// line 124 - padding content for AES004 file too large violation
// line 125 - padding content for AES004 file too large violation
// line 126 - padding content for AES004 file too large violation
// line 127 - padding content for AES004 file too large violation
// line 128 - padding content for AES004 file too large violation
// line 129 - padding content for AES004 file too large violation
// line 130 - padding content for AES004 file too large violation
// line 131 - padding content for AES004 file too large violation
// line 132 - padding content for AES004 file too large violation
// line 133 - padding content for AES004 file too large violation
// line 134 - padding content for AES004 file too large violation
// line 135 - padding content for AES004 file too large violation
// line 136 - padding content for AES004 file too large violation
// line 137 - padding content for AES004 file too large violation
// line 138 - padding content for AES004 file too large violation
// line 139 - padding content for AES004 file too large violation
// line 140 - padding content for AES004 file too large violation
// line 141 - padding content for AES004 file too large violation
// line 142 - padding content for AES004 file too large violation
// line 143 - padding content for AES004 file too large violation
// line 144 - padding content for AES004 file too large violation
// line 145 - padding content for AES004 file too large violation
// line 146 - padding content for AES004 file too large violation
// line 147 - padding content for AES004 file too large violation
// line 148 - padding content for AES004 file too large violation
// line 149 - padding content for AES004 file too large violation
// line 150 - padding content for AES004 file too large violation
// line 151 - padding content for AES004 file too large violation
// line 152 - padding content for AES004 file too large violation
// line 153 - padding content for AES004 file too large violation
// line 154 - padding content for AES004 file too large violation
// line 155 - padding content for AES004 file too large violation
// line 156 - padding content for AES004 file too large violation
// line 157 - padding content for AES004 file too large violation
// line 158 - padding content for AES004 file too large violation
// line 159 - padding content for AES004 file too large violation
// line 160 - padding content for AES004 file too large violation
// line 161 - padding content for AES004 file too large violation
// line 162 - padding content for AES004 file too large violation
// line 163 - padding content for AES004 file too large violation
// line 164 - padding content for AES004 file too large violation
// line 165 - padding content for AES004 file too large violation
// line 166 - padding content for AES004 file too large violation
// line 167 - padding content for AES004 file too large violation
// line 168 - padding content for AES004 file too large violation
// line 169 - padding content for AES004 file too large violation
// line 170 - padding content for AES004 file too large violation
// line 171 - padding content for AES004 file too large violation
// line 172 - padding content for AES004 file too large violation
// line 173 - padding content for AES004 file too large violation
// line 174 - padding content for AES004 file too large violation
// line 175 - padding content for AES004 file too large violation
// line 176 - padding content for AES004 file too large violation
// line 177 - padding content for AES004 file too large violation
// line 178 - padding content for AES004 file too large violation
// line 179 - padding content for AES004 file too large violation
// line 180 - padding content for AES004 file too large violation
// line 181 - padding content for AES004 file too large violation
// line 182 - padding content for AES004 file too large violation
// line 183 - padding content for AES004 file too large violation
// line 184 - padding content for AES004 file too large violation
// line 185 - padding content for AES004 file too large violation
// line 186 - padding content for AES004 file too large violation
// line 187 - padding content for AES004 file too large violation
// line 188 - padding content for AES004 file too large violation
// line 189 - padding content for AES004 file too large violation
// line 190 - padding content for AES004 file too large violation
// line 191 - padding content for AES004 file too large violation
// line 192 - padding content for AES004 file too large violation
// line 193 - padding content for AES004 file too large violation
// line 194 - padding content for AES004 file too large violation
// line 195 - padding content for AES004 file too large violation
// line 196 - padding content for AES004 file too large violation
// line 197 - padding content for AES004 file too large violation
// line 198 - padding content for AES004 file too large violation
// line 199 - padding content for AES004 file too large violation
// line 200 - padding content for AES004 file too large violation
// line 201 - padding content for AES004 file too large violation
// line 202 - padding content for AES004 file too large violation
// line 203 - padding content for AES004 file too large violation
// line 204 - padding content for AES004 file too large violation
// line 205 - padding content for AES004 file too large violation
// line 206 - padding content for AES004 file too large violation
// line 207 - padding content for AES004 file too large violation
// line 208 - padding content for AES004 file too large violation
// line 209 - padding content for AES004 file too large violation
// line 210 - padding content for AES004 file too large violation
// line 211 - padding content for AES004 file too large violation
// line 212 - padding content for AES004 file too large violation
// line 213 - padding content for AES004 file too large violation
// line 214 - padding content for AES004 file too large violation
// line 215 - padding content for AES004 file too large violation
// line 216 - padding content for AES004 file too large violation
// line 217 - padding content for AES004 file too large violation
// line 218 - padding content for AES004 file too large violation
// line 219 - padding content for AES004 file too large violation
// line 220 - padding content for AES004 file too large violation
// line 221 - padding content for AES004 file too large violation
// line 222 - padding content for AES004 file too large violation
// line 223 - padding content for AES004 file too large violation
// line 224 - padding content for AES004 file too large violation
// line 225 - padding content for AES004 file too large violation
// line 226 - padding content for AES004 file too large violation
// line 227 - padding content for AES004 file too large violation
// line 228 - padding content for AES004 file too large violation
// line 229 - padding content for AES004 file too large violation
// line 230 - padding content for AES004 file too large violation
// line 231 - padding content for AES004 file too large violation
// line 232 - padding content for AES004 file too large violation
// line 233 - padding content for AES004 file too large violation
// line 234 - padding content for AES004 file too large violation
// line 235 - padding content for AES004 file too large violation
// line 236 - padding content for AES004 file too large violation
// line 237 - padding content for AES004 file too large violation
// line 238 - padding content for AES004 file too large violation
// line 239 - padding content for AES004 file too large violation
// line 240 - padding content for AES004 file too large violation
// line 241 - padding content for AES004 file too large violation
// line 242 - padding content for AES004 file too large violation
// line 243 - padding content for AES004 file too large violation
// line 244 - padding content for AES004 file too large violation
// line 245 - padding content for AES004 file too large violation
// line 246 - padding content for AES004 file too large violation
// line 247 - padding content for AES004 file too large violation
// line 248 - padding content for AES004 file too large violation
// line 249 - padding content for AES004 file too large violation
// line 250 - padding content for AES004 file too large violation
// line 251 - padding content for AES004 file too large violation
// line 252 - padding content for AES004 file too large violation
// line 253 - padding content for AES004 file too large violation
// line 254 - padding content for AES004 file too large violation
// line 255 - padding content for AES004 file too large violation
// line 256 - padding content for AES004 file too large violation
// line 257 - padding content for AES004 file too large violation
// line 258 - padding content for AES004 file too large violation
// line 259 - padding content for AES004 file too large violation
// line 260 - padding content for AES004 file too large violation
// line 261 - padding content for AES004 file too large violation
// line 262 - padding content for AES004 file too large violation
// line 263 - padding content for AES004 file too large violation
// line 264 - padding content for AES004 file too large violation
// line 265 - padding content for AES004 file too large violation
// line 266 - padding content for AES004 file too large violation
// line 267 - padding content for AES004 file too large violation
// line 268 - padding content for AES004 file too large violation
// line 269 - padding content for AES004 file too large violation
// line 270 - padding content for AES004 file too large violation
// line 271 - padding content for AES004 file too large violation
// line 272 - padding content for AES004 file too large violation
// line 273 - padding content for AES004 file too large violation
// line 274 - padding content for AES004 file too large violation
// line 275 - padding content for AES004 file too large violation
// line 276 - padding content for AES004 file too large violation
// line 277 - padding content for AES004 file too large violation
// line 278 - padding content for AES004 file too large violation
// line 279 - padding content for AES004 file too large violation
// line 280 - padding content for AES004 file too large violation
// line 281 - padding content for AES004 file too large violation
// line 282 - padding content for AES004 file too large violation
// line 283 - padding content for AES004 file too large violation
// line 284 - padding content for AES004 file too large violation
// line 285 - padding content for AES004 file too large violation
// line 286 - padding content for AES004 file too large violation
// line 287 - padding content for AES004 file too large violation
// line 288 - padding content for AES004 file too large violation
// line 289 - padding content for AES004 file too large violation
// line 290 - padding content for AES004 file too large violation
// line 291 - padding content for AES004 file too large violation
// line 292 - padding content for AES004 file too large violation
// line 293 - padding content for AES004 file too large violation
// line 294 - padding content for AES004 file too large violation
// line 295 - padding content for AES004 file too large violation
// line 296 - padding content for AES004 file too large violation
// line 297 - padding content for AES004 file too large violation
// line 298 - padding content for AES004 file too large violation
// line 299 - padding content for AES004 file too large violation
// line 300 - padding content for AES004 file too large violation
// line 301 - padding content for AES004 file too large violation
// line 302 - padding content for AES004 file too large violation
// line 303 - padding content for AES004 file too large violation
// line 304 - padding content for AES004 file too large violation
// line 305 - padding content for AES004 file too large violation
// line 306 - padding content for AES004 file too large violation
// line 307 - padding content for AES004 file too large violation
// line 308 - padding content for AES004 file too large violation
// line 309 - padding content for AES004 file too large violation
// line 310 - padding content for AES004 file too large violation
// line 311 - padding content for AES004 file too large violation
// line 312 - padding content for AES004 file too large violation
// line 313 - padding content for AES004 file too large violation
// line 314 - padding content for AES004 file too large violation
// line 315 - padding content for AES004 file too large violation
// line 316 - padding content for AES004 file too large violation
// line 317 - padding content for AES004 file too large violation
// line 318 - padding content for AES004 file too large violation
// line 319 - padding content for AES004 file too large violation
// line 320 - padding content for AES004 file too large violation
// line 321 - padding content for AES004 file too large violation
// line 322 - padding content for AES004 file too large violation
// line 323 - padding content for AES004 file too large violation
// line 324 - padding content for AES004 file too large violation
// line 325 - padding content for AES004 file too large violation
// line 326 - padding content for AES004 file too large violation
// line 327 - padding content for AES004 file too large violation
// line 328 - padding content for AES004 file too large violation
// line 329 - padding content for AES004 file too large violation
// line 330 - padding content for AES004 file too large violation
// line 331 - padding content for AES004 file too large violation
// line 332 - padding content for AES004 file too large violation
// line 333 - padding content for AES004 file too large violation
// line 334 - padding content for AES004 file too large violation
// line 335 - padding content for AES004 file too large violation
// line 336 - padding content for AES004 file too large violation
// line 337 - padding content for AES004 file too large violation
// line 338 - padding content for AES004 file too large violation
// line 339 - padding content for AES004 file too large violation
// line 340 - padding content for AES004 file too large violation
// line 341 - padding content for AES004 file too large violation
// line 342 - padding content for AES004 file too large violation
// line 343 - padding content for AES004 file too large violation
// line 344 - padding content for AES004 file too large violation
// line 345 - padding content for AES004 file too large violation
// line 346 - padding content for AES004 file too large violation
// line 347 - padding content for AES004 file too large violation
// line 348 - padding content for AES004 file too large violation
// line 349 - padding content for AES004 file too large violation
// line 350 - padding content for AES004 file too large violation
// line 351 - padding content for AES004 file too large violation
// line 352 - padding content for AES004 file too large violation
// line 353 - padding content for AES004 file too large violation
// line 354 - padding content for AES004 file too large violation
// line 355 - padding content for AES004 file too large violation
// line 356 - padding content for AES004 file too large violation
// line 357 - padding content for AES004 file too large violation
// line 358 - padding content for AES004 file too large violation
// line 359 - padding content for AES004 file too large violation
// line 360 - padding content for AES004 file too large violation
// line 361 - padding content for AES004 file too large violation
// line 362 - padding content for AES004 file too large violation
// line 363 - padding content for AES004 file too large violation
// line 364 - padding content for AES004 file too large violation
// line 365 - padding content for AES004 file too large violation
// line 366 - padding content for AES004 file too large violation
// line 367 - padding content for AES004 file too large violation
// line 368 - padding content for AES004 file too large violation
// line 369 - padding content for AES004 file too large violation
// line 370 - padding content for AES004 file too large violation
// line 371 - padding content for AES004 file too large violation
// line 372 - padding content for AES004 file too large violation
// line 373 - padding content for AES004 file too large violation
// line 374 - padding content for AES004 file too large violation
// line 375 - padding content for AES004 file too large violation
// line 376 - padding content for AES004 file too large violation
// line 377 - padding content for AES004 file too large violation
// line 378 - padding content for AES004 file too large violation
// line 379 - padding content for AES004 file too large violation
// line 380 - padding content for AES004 file too large violation
// line 381 - padding content for AES004 file too large violation
// line 382 - padding content for AES004 file too large violation
// line 383 - padding content for AES004 file too large violation
// line 384 - padding content for AES004 file too large violation
// line 385 - padding content for AES004 file too large violation
// line 386 - padding content for AES004 file too large violation
// line 387 - padding content for AES004 file too large violation
// line 388 - padding content for AES004 file too large violation
// line 389 - padding content for AES004 file too large violation
// line 390 - padding content for AES004 file too large violation
// line 391 - padding content for AES004 file too large violation
// line 392 - padding content for AES004 file too large violation
// line 393 - padding content for AES004 file too large violation
// line 394 - padding content for AES004 file too large violation
// line 395 - padding content for AES004 file too large violation
// line 396 - padding content for AES004 file too large violation
// line 397 - padding content for AES004 file too large violation
// line 398 - padding content for AES004 file too large violation
// line 399 - padding content for AES004 file too large violation
// line 400 - padding content for AES004 file too large violation
// line 401 - padding content for AES004 file too large violation
// line 402 - padding content for AES004 file too large violation
// line 403 - padding content for AES004 file too large violation
// line 404 - padding content for AES004 file too large violation
// line 405 - padding content for AES004 file too large violation
// line 406 - padding content for AES004 file too large violation
// line 407 - padding content for AES004 file too large violation
// line 408 - padding content for AES004 file too large violation
// line 409 - padding content for AES004 file too large violation
// line 410 - padding content for AES004 file too large violation
// line 411 - padding content for AES004 file too large violation
// line 412 - padding content for AES004 file too large violation
// line 413 - padding content for AES004 file too large violation
// line 414 - padding content for AES004 file too large violation
// line 415 - padding content for AES004 file too large violation
// line 416 - padding content for AES004 file too large violation
// line 417 - padding content for AES004 file too large violation
// line 418 - padding content for AES004 file too large violation
// line 419 - padding content for AES004 file too large violation
// line 420 - padding content for AES004 file too large violation
// line 421 - padding content for AES004 file too large violation
// line 422 - padding content for AES004 file too large violation
// line 423 - padding content for AES004 file too large violation
// line 424 - padding content for AES004 file too large violation
// line 425 - padding content for AES004 file too large violation
// line 426 - padding content for AES004 file too large violation
// line 427 - padding content for AES004 file too large violation
// line 428 - padding content for AES004 file too large violation
// line 429 - padding content for AES004 file too large violation
// line 430 - padding content for AES004 file too large violation
// line 431 - padding content for AES004 file too large violation
// line 432 - padding content for AES004 file too large violation
// line 433 - padding content for AES004 file too large violation
// line 434 - padding content for AES004 file too large violation
// line 435 - padding content for AES004 file too large violation
// line 436 - padding content for AES004 file too large violation
// line 437 - padding content for AES004 file too large violation
// line 438 - padding content for AES004 file too large violation
// line 439 - padding content for AES004 file too large violation
// line 440 - padding content for AES004 file too large violation
// line 441 - padding content for AES004 file too large violation
// line 442 - padding content for AES004 file too large violation
// line 443 - padding content for AES004 file too large violation
// line 444 - padding content for AES004 file too large violation
// line 445 - padding content for AES004 file too large violation
// line 446 - padding content for AES004 file too large violation
// line 447 - padding content for AES004 file too large violation
// line 448 - padding content for AES004 file too large violation
// line 449 - padding content for AES004 file too large violation
// line 450 - padding content for AES004 file too large violation
// line 451 - padding content for AES004 file too large violation
// line 452 - padding content for AES004 file too large violation
// line 453 - padding content for AES004 file too large violation
// line 454 - padding content for AES004 file too large violation
// line 455 - padding content for AES004 file too large violation
// line 456 - padding content for AES004 file too large violation
// line 457 - padding content for AES004 file too large violation
// line 458 - padding content for AES004 file too large violation
// line 459 - padding content for AES004 file too large violation
// line 460 - padding content for AES004 file too large violation
// line 461 - padding content for AES004 file too large violation
// line 462 - padding content for AES004 file too large violation
// line 463 - padding content for AES004 file too large violation
// line 464 - padding content for AES004 file too large violation
// line 465 - padding content for AES004 file too large violation
// line 466 - padding content for AES004 file too large violation
// line 467 - padding content for AES004 file too large violation
// line 468 - padding content for AES004 file too large violation
// line 469 - padding content for AES004 file too large violation
// line 470 - padding content for AES004 file too large violation
// line 471 - padding content for AES004 file too large violation
// line 472 - padding content for AES004 file too large violation
// line 473 - padding content for AES004 file too large violation
// line 474 - padding content for AES004 file too large violation
// line 475 - padding content for AES004 file too large violation
// line 476 - padding content for AES004 file too large violation
// line 477 - padding content for AES004 file too large violation
// line 478 - padding content for AES004 file too large violation
// line 479 - padding content for AES004 file too large violation
// line 480 - padding content for AES004 file too large violation
// line 481 - padding content for AES004 file too large violation
// line 482 - padding content for AES004 file too large violation
// line 483 - padding content for AES004 file too large violation
// line 484 - padding content for AES004 file too large violation
// line 485 - padding content for AES004 file too large violation
// line 486 - padding content for AES004 file too large violation
// line 487 - padding content for AES004 file too large violation
// line 488 - padding content for AES004 file too large violation
// line 489 - padding content for AES004 file too large violation
// line 490 - padding content for AES004 file too large violation
// line 491 - padding content for AES004 file too large violation
// line 492 - padding content for AES004 file too large violation
// line 493 - padding content for AES004 file too large violation
// line 494 - padding content for AES004 file too large violation
// line 495 - padding content for AES004 file too large violation
// line 496 - padding content for AES004 file too large violation
// line 497 - padding content for AES004 file too large violation
// line 498 - padding content for AES004 file too large violation
// line 499 - padding content for AES004 file too large violation
// line 500 - padding content for AES004 file too large violation
// line 501 - padding content for AES004 file too large violation
// line 502 - padding content for AES004 file too large violation
// line 503 - padding content for AES004 file too large violation
// line 504 - padding content for AES004 file too large violation
// line 505 - padding content for AES004 file too large violation
// line 506 - padding content for AES004 file too large violation
// line 507 - padding content for AES004 file too large violation
// line 508 - padding content for AES004 file too large violation
// line 509 - padding content for AES004 file too large violation
// line 510 - padding content for AES004 file too large violation

export class OverlargeDomainEntity {
    id: number;
    name: string;
    constructor(id: number, name: string) {
        this.id = id;
        this.name = name;
    }
}
