use crate::tui::taxonomy_state_vo::PanelFocus;

pub const DEFAULT_FOCUS: PanelFocus = PanelFocus::FileList;

#[derive(Debug, Clone, PartialEq)]
pub enum TuiEvent {
    MoveUp,
    MoveDown,
    MoveTop,
    MoveBottom,
    NavigateBack,
    NavigateForward,
    FocusNext,
    FocusPrev,
    ActionCheck,
    ActionScan,
    ActionFix,
    ActionCi,
    ActionWatch,
    ActionOrphan,
    ActionSecurity,
    ActionDuplicates,
    ActionDependencies,
    ActionDoctor,
    ActionInit,
    ActionInstall,
    ActionMcpConfig,
    ActionConfigShow,
    ActionInstallHook,
    ActionUninstallHook,
    ActionAdapters,
    ActionVersion,
    ToggleHelp,
    ToggleSearch,
    SearchInput(char),
    SearchBackspace,
    SearchConfirm,
    SearchCancel,
    PathInput(char),
    PathBackspace,
    PathConfirm,
    PathUseCurrent,
    Quit,
    Resize(u16, u16),
    MouseClick(u16, u16),
    MouseScrollUp,
    MouseScrollDown,
    CopyToClipboard,
    CopyToFile,
    PreviewScrollUp,
    PreviewScrollDown,
    Tick,
    None,
}
