#[path = "auto-fix/src/mod.rs"]
pub mod auto_fix;
#[path = "cli-commands/src/mod.rs"]
// PURPOSE: Library root — exports public API modules for CLI and MCP targets
pub mod cli_commands;
#[path = "cli-transport/src/mod.rs"]
pub mod cli_transport;
#[path = "code-analysis/src/mod.rs"]
pub mod code_analysis;
#[path = "config-system/src/mod.rs"]
pub mod config_system;
#[path = "di-containers/src/mod.rs"]
pub mod di_containers;
#[path = "file-system/src/mod.rs"]
pub mod file_system;
#[path = "file-watch/src/mod.rs"]
pub mod file_watch;
#[path = "git-hooks/src/mod.rs"]
pub mod git_hooks;
#[path = "import-rules/src/mod.rs"]
pub mod import_rules;
#[path = "language-adapters/src/mod.rs"]
pub mod language_adapters;
#[path = "naming-rules/src/mod.rs"]
pub mod naming_rules;

#[path = "lifecycle-state/src/mod.rs"]
pub mod lifecycle_state;
#[path = "mcp-server/src/mod.rs"]
pub mod mcp_server;
#[path = "metrics-service/src/mod.rs"]
pub mod metrics_service;
#[path = "multi-project/src/mod.rs"]
pub mod multi_project;

#[path = "orphan-detector/src/mod.rs"]
pub mod orphan_detector;
#[path = "output-report/src/mod.rs"]
pub mod output_report;
#[path = "pipeline-jobs/src/mod.rs"]
pub mod pipeline_jobs;
#[path = "plugin-system/src/mod.rs"]
pub mod plugin_system;
#[path = "project-setup/src/mod.rs"]
pub mod project_setup;
#[path = "role-rules/src/mod.rs"]
pub mod role_rules;
#[path = "shared-common/src/mod.rs"]
pub mod shared_common;
#[path = "source-parsing/src/mod.rs"]
pub mod source_parsing;

// Composition root — wraps all feature containers, implements ServiceContainerAggregate
pub mod composition_root;

// Feature containers (root layer, wiring only)
#[path = "code-analysis/analysis_container.rs"]
pub mod analysis_container;
#[path = "auto-fix/auto_fix_container.rs"]
pub mod auto_fix_container;
#[path = "config-system/config_container.rs"]
pub mod config_container;
#[path = "file-system/file_container.rs"]
pub mod file_container;
#[path = "git-hooks/git_container.rs"]
pub mod git_container;
#[path = "import-rules/import_container.rs"]
pub mod import_container;
#[path = "language-adapters/language_container.rs"]
pub mod language_container;
#[path = "lifecycle-state/lifecycle_container.rs"]
pub mod lifecycle_container;
#[path = "mcp-server/mcp_container.rs"]
pub mod mcp_container;
#[path = "metrics-service/metrics_container.rs"]
pub mod metrics_container;
#[path = "multi-project/multi_project_container.rs"]
pub mod multi_project_container;
#[path = "naming-rules/naming_container.rs"]
pub mod naming_container;
#[path = "orphan-detector/orphan_container.rs"]
pub mod orphan_container;
#[path = "output-report/output_container.rs"]
pub mod output_container;
#[path = "pipeline-jobs/pipeline_container.rs"]
pub mod pipeline_container;
#[path = "plugin-system/plugin_container.rs"]
pub mod plugin_container;
#[path = "role-rules/role_container.rs"]
pub mod role_container;
#[path = "project-setup/setup_container.rs"]
pub mod setup_container;
#[path = "source-parsing/source_parsing_container.rs"]
pub mod source_parsing_container;
#[path = "cli-transport/transport_container.rs"]
pub mod transport_container;
