// AES406: surface with too many control flow statements
pub fn handler() {
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
    if true {} else {}
}
